<?
/**
 * @var product_item $product
 */
?>
<a href="<?= $product->obProduct->getUrl() ?>" data-id="<?= $product->obProduct->product_id ?>" data-name="<?= htmlspecialchars($product->obProduct->product_name) ?>"
        data-url="<?= $product->obProduct->getUrl($product->urlParams) ?>">
    <img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" class="image lazyload" alt="<?= $product->obProduct->full_name ?>"
            data-src="<?= $product->obProduct->getPhoto("dynamic") ?>" data-sizes="auto" data-widths="[182,190,320,380,520,720]"/>
    <div class="itemInfo">
        <? if ($product->showName) { ?>
            <h5 class="name">
                <? if ($product->showBrand) { ?>
                    <span class="brandName"><?= $product->obProduct->brand_name ?></span>
                <? } ?>
                <?= $product->obProduct->product_name ?>
            </h5>
        <? } ?>
        <div class="priceBox">
            <p class="price"><?= icms::format_money($product->obProduct->getSalePrice(), 'TL', true) ?></p>
            <? if ($product->showBasePrice) { ?>
                <p class="old-price"><?= icms::format_money($product->obProduct->getBasePrice(), 'TL', true) ?></p>
            <? } ?>
            <? if ($product->obProduct->hasBadge(ob_product::BADGE_DISCOUNT)) { ?>
                <div class="discount-percent">
                    <span class="discount-icon">%</span><span class="discount-amount"><?= $product->obProduct->getDiscountPercent() ?></span>
                    <span class="discount-text">i̇ndi̇ri̇m</span>
                </div>
            <? } ?>
        </div>
        <? $rating = $product->obProduct->getRating(); ?>
        <? if ($rating->getCount() > 0) { ?>
            <div class="rating">
                <div class="stars" data-score="<?= $rating->getScore() ?>" data-readonly="true"></div>
            </div>
        <? } ?>
    </div>
    <? if ($product->freeShipping && $product->obProduct->hasBadge(ob_product::BADGE_FREE_SHIPPING)) { ?>
        <div class="badge ucretsiz-kargo">
            <div class="option">
                <span class="sprite"></span>
            </div>
        </div>
    <? } ?>
    <div class="badges">
        <? if ($product->obProduct->hasBadge(ob_product::BADGE_NEW)) { ?>
            <div class="badge new-product">
                <div class="option">
                    <span class="sprite"></span>
                </div>
            </div>
        <? } ?>
        <? if ($product->fastShipping && $product->obProduct->hasBadge(ob_product::BADGE_FAST_CARGO)) { ?>
            <div class="badge ayni-gun-kargo">
                <div class="option">
                    <span class="sprite"></span>
                </div>
            </div>
        <? } ?>
        <? if ($product->obProduct->hasBadge(ob_product::BADGE_CAMPAIGN)) { ?>
            <div class="badge kampanya">
                <div class="option">
                    <span class="sprite"></span>
                </div>
            </div>
        <? } ?>
    </div>
</a>
