<?
/**
 * @var product_item $product
 */
?>
<a href="<?= $product->obProduct->getUrl() ?>" data-id="<?= $product->obProduct->product_id ?>" data-name="<?= htmlspecialchars($product->obProduct->product_name) ?>"
    data-url="<?= $product->obProduct->getUrl($product->urlParams) ?>">
    <img class="image" src="<?= $product->obProduct->getPhoto("catalog") ?>">
    <? if ($product->showName) { ?>
        <h5 class="name">
            <? if ($product->showBrand) { ?>
                <span class="brandName"><?= $product->obProduct->brand_name ?></span>
            <? } ?>
            <?= $product->obProduct->product_name ?>
        </h5>
    <? } ?>
    <? if ($product->showBasePrice) { ?>
        <p class="old-price"><?= icms::format_money($product->obProduct->getBasePrice()) ?></p>
    <? } ?>
    <p class="price"><?= icms::format_money($product->obProduct->getSalePrice()) ?></p>
    <? $rating = $product->obProduct->getRating(); ?>
    <? if ($rating->getCount() > 0) { ?>
        <div class="rating">
            <div class="stars" data-score="<?= $rating->getScore() ?>" data-readonly="true"></div>
        </div>
    <? } ?>
    <? if ($product->obProduct->hasBadge(ob_product::BADGE_DISCOUNT)) { ?>
        <div class="discount-percent">
            <span class="discount-icon">%</span><?= $product->obProduct->getDiscountPercent() ?><span class="discount-text">İNDİRİM</span>
        </div>
    <? } ?>
    <? if ($product->freeShipping && $product->obProduct->hasBadge(ob_product::BADGE_FREE_SHIPPING)) { ?>
        <div class="badge free-cargo">
            <div class="option"><span class="sprite"></span><span class="text">ÜCRETSİZ KARGO</span></div>
        </div>
    <? } ?>
    <? if ($product->fastShipping && $product->obProduct->hasBadge(ob_product::BADGE_FAST_CARGO)) { ?>
        <div class="badge fast-cargo">
            <div class="option"><span class="sprite"></span><span class="text">HIZLI KARGO</span></div>
        </div>
    <? } ?>
    <? if ($product->obProduct->hasBadge(ob_product::BADGE_NEW)) { ?>
        <div class="badge new-product">
            <div class="option"><span class="sprite"></span><span class="text">YENİ ÜRÜN</span></div>
        </div>
    <? } ?>
</a>
