<?
/**
 * @var array $searcCategories
 */
?>
<div class="input-group-btn" id="catSelectBox">
    <button type="button" class="btn btn-default dropdown-toggle hidden-xs" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span id="selectedCategoryName">Tüm Kategorilerde</span>
        <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" role="menu">
        <? foreach ($searcCategories as $catId => $category) { ?>
            <li><a href="javascript:" data-cat="<?= $catId ?>"><?= $category ?></a></li>
        <? } ?>
        <li class="divider"></li>
        <li><a href="javascript:" data-cat="0">Tüm Kategorilerde</a></li>
    </ul>
</div>
