<?
/**
 * @var ob_product                           $obProduct
 * @var array                                $productGroupLinks
 * @var bool                                 $hasVariants
 * @var array                                $variantProperties
 * @var array                                $productPhotos
 * @var string                               $mainProductName
 * @var int                                  $mainProductId
 * @var string                               $mainProductUrl
 * @var string                               $FacebookAppID
 * @var string                               $TwitterAccount
 * @var \TeknoETicaret\Object\Product\Rating $rating
 * @var int                                  $reviewCount
 * @var bool                                 $hasVisiblePriceCampaign
 * @var bool                                 $hasAvailableShoppingCheck
 * @var bool                                 $inStock
 * @var array                                $productHasProperty
 * @var stdClass                             $reviewData
 * @var float                                $minInstallmentAmount
 * @var int                                  $maxInstallmentCount
 * @var string                               $semanticData
 * @var array                                $widgets
 * @var string                               $tabs
 */
?>
<? view::show_breadcrumbs(); ?>
<h1 class="product-title"><?= $mainProductName ?></h1>
<div class="row mb-30">
    <div class="col-sm-6 mmb30">
        <div class="block product-image-wrapper">
            <!-- thumbnails -->
            <div class="col-lg-2 col-md-3 col-sm-12 col-xs-12  <?= (count($productPhotos) < 7 ? "noCarousel" : "") ?>" id="thumbnailContainer">
                <a href="javascript:" onclick="thumbnailCarouselPrev(thumbItemCount)" class="sprite sliderArrow arrowUp"></a>
                <div id="thumbnailCarousel">
                    <? foreach ($productPhotos as $key => $photo) { ?>
                        <a href="javascript:" class="productThumbImage<?= ($key == 0 ? ' active' : '') ?>" data-image="<?= $photo['normal'] ?>"
                                data-zoom-image="<?= $photo['big'] ?>">
                            <img id="gallery" width="59" height="59" src="<?= $photo['thumb'] ?>"/> </a>
                    <? } ?>
                </div>
                <a href="javascript:" onclick="thumbnailCarouselNext(thumbItemCount)" class="sprite sliderArrow arrowDown"></a>
            </div>
            <!-- #thumbnails# -->
            <div class="col-lg-10 col-md-9 col-sm-12">
                <div class="productImages">
                    <div id="zoomContainer">
                        <img id="activeImage" src="<?= $obProduct->getPhoto("normal") ?>" data-zoom-image="<?= $obProduct->getPhoto("big") ?>"/>
                    </div>
                    <script>
                        var thumbItemCount = 5;
                        $(function () {
                            function initEZPlus() {
                                while ($('.zoomWrapper #activeImage').length > 0) {
                                    $('.zoomWrapper #activeImage').unwrap();
                                }
                                $('.zoomContainer').remove();
                                $('.ezp-spinner').remove();
                                $("#activeImage")
                                    .removeData('ezPlus')
                                    .ezPlus({
                                        gallery: 'thumbnailCarousel',
                                        galleryActiveClass: 'active',
                                        loadingIcon: '/assets/elevatezoom-plus/ajax-loader.gif',
                                        zoomType: "inner",
                                        borderSize: 0,
                                        scrollZoom: true,
                                        respond: [
                                            {
                                                range: '100-699',
                                                enabled: true,
                                                scrollZoom: false,
                                                showLens: false
                                            }
                                        ]
                                    });
                            }

                            $(document).on('oasis.resize', function () {
                                initEZPlus();
                                fitHeight(".product-details-container", ".product-image-wrapper");
                                if ($(window).innerWidth() > 767) {
                                    thumbItemCount = 5;
                                } else {
                                    thumbItemCount = 3;
                                }
                            });
                        });
                    </script>
                </div><!-- #productImages# -->
            </div><!-- #col# -->
            <div class="share">
                <?= implode('', view::getShareIcons($mainProductUrl, 'sprite')) ?>
                <? if (session::isStaff()) { ?>
                    <a title="Ürünü Düzenle" data-toggle="tooltip" data-placement="bottom" target="_blank" style="font-size:18px"
                            href="<?= app::getUrl(app::APP_TAG_OASIS, 'http') . "/product/summary/" . $obProduct->product_id ?>"><i class="glyphicon glyphicon-edit"></i></a>
                <? } ?>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
    <div class="col-sm-6 product-details-container mmb30">
        <div class="block">
            <? if ($obProduct->is_saleable || \TeknoETicaret\Config\Settings::get('product.notsaleable.showprice') == 1) { ?>
                <div class="price-wrapper">
                    <? if ($obProduct->hasBadge(ob_product::BADGE_DISCOUNT)) { ?>
                        <div class="discount-percent pull-left sprite">
                            <span class="discount-icon">%</span><?= $obProduct->getDiscountPercent() ?><span class="discount-text">İNDİRİM</span>
                        </div>
                    <? } ?>
                    <div class="pull-right">
                        <? if ($obProduct->hasBadge(ob_product::BADGE_DISCOUNT)) { ?>
                            <div class="item-price-old"><?= icms::format_money($obProduct->getBasePrice(), 'TL', true) ?></div>
                        <? } ?>
                        <div class="product-price">
                            <?= icms::format_money($obProduct->getSalePrice(), 'TL', true) ?>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            <? } ?>
            <div class="product-row">
                <div class="product-info-cont">
                    <? if ($obProduct->hasBadge(ob_product::BADGE_FREE_SHIPPING)) { ?>
                        <div class="product-info-col badge free-cargo ml10">
                            <span class="sprite"></span>ÜCRETSİZ KARGO
                        </div>
                    <? } else { ?>
                        <div class="badge cargo ml10">
                            <span class="sprite"></span>Kargo Ücreti <?= icms::format_money($obProduct->getShippingCost()) ?>
                        </div>
                    <? } ?>
                    <div class="product-info-right">
                        <div class="comment-link">
                            <a href="#tabReviews" onclick="showTab('comments')"><span class="sprite comment"></span>Yorum ve Soru
                                <span id="commentCount">(<?= $reviewCount ?>)</span></a>
                        </div>
                        <div class="star">
                            <div class="productRating" style="cursor: pointer;"></div>
                            <script type="text/javascript">
                                $(function () {
                                    $('.productRating').raty({
                                        score: <?= $rating->getScore() ?>,
                                        click: function (score) {
                                            $.post('/product/saveRating', {product_id: '<?=$mainProductId ?>', rating_score: score}, function (data) {
                                                if (data.readonly) {
                                                    $('.productRating').raty({readOnly: true, score: <?= $rating->getScore() ?>});
                                                }
                                                if (typeof data.message !== "undefined") {
                                                    alert(data.message);
                                                }
                                            });
                                        }
                                    });
                                });
                            </script>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
            <? if (count($productGroupLinks)) { ?>
                <? foreach ($productGroupLinks as $propertyId => $propertyData) { ?>
                    <div class="product-row">
                        <div class="product-options">
                            <label><?= $propertyData['name'] ?></label>
                            <ul class="nav">
                                <? foreach ($propertyData['options'] AS $optionId => $optionData) { ?>
                                    <li <?= ((isset($propertyData['selectedOption']) && $propertyData['selectedOption'] == $optionData['option_id']) ? 'class="active"' : '') ?>>
                                        <a href="<?= $optionData['url'] ?>"><?= $optionData['name'] ?><span class="price"><?= icms::format_money($optionData['price']) ?></span></a>
                                    </li>
                                <? } ?>
                            </ul>
                        </div>
                    </div>
                <? } ?>
            <? } ?>
            <div id="productData">
                <? if ($hasVariants) { ?>
                    <form role="form" action="<?= $mainProductUrl ?>" method="POST" id="formVariant" data-rel="ajax" data-callback="propertyFormCallback">
                        <? foreach ($variantProperties as $propertyId => $propertyData) { ?>
                            <div class="product-row">
                                <div class="product-options">
                                    <input type="hidden" name="property[<?= $propertyId ?>]" value="<?= $propertyData['selected'] ?>">
                                    <label><?= $propertyData['name'] ?></label>
                                    <ul class="nav">
                                        <? foreach ($propertyData['options'] AS $optionId => $optionData) { ?>
                                            <li <?= ($propertyData['selected'] == $optionId ? 'class="active"' : '') ?> id="property-<?= $propertyId ?>-<?= $optionId ?>"><a
                                                        href="javascript:" onclick="chooseProperty('<?= $propertyId ?>', '<?= $optionId ?>')"><?= $optionData['name'] ?>
                                                    <? if (!$propertyData['samePrice']) { ?>
                                                        <? if ($optionData['saleable']) { ?>
                                                            <span class="price"><?= icms::format_money($optionData['price']) ?></span>
                                                        <? } else { ?>
                                                            <span>TÜKENDİ</span>
                                                        <? } ?>
                                                    <? } ?>
                                                </a>
                                            </li>
                                        <? } ?>
                                    </ul>
                                </div>
                            </div>
                        <? } ?>
                    </form>
                <? } ?>
                <? if ($obProduct->is_saleable && $maxInstallmentCount > 1) { ?>
                    <div class="product-row">
                        <div class="product-instalment">
                            <?= icms::format_money($minInstallmentAmount) ?>'den başlayan taksit seçenekleri
                        </div>
                    </div>
                <? } ?>
                <? if ($obProduct->hasBadge(ob_product::BADGE_NEW) || $obProduct->hasBadge(ob_product::BADGE_FAST_CARGO)) { ?>
                    <div class="product-row">
                        <div class="product-mid-badges">
                            <? if ($obProduct->hasBadge(ob_product::BADGE_NEW)) { ?>
                                <div class="pull-left ml10">
                                    <span class="sprite sprite-product chance"></span> Yeni Ürün
                                </div>
                            <? } ?>
                            <? if ($obProduct->hasBadge(ob_product::BADGE_FAST_CARGO)) { ?>
                                <div class="pull-left ml10">
                                    <span class="sprite sprite-product fast-cargo"></span>
                                    <?= (($obProduct->warehouse_stock > 0 && $obProduct->warehouse_stock <= 5) ? 'Son ' . $obProduct->warehouse_stock . ' Ürün' : 'Hızlı Kargo') ?>
                                </div>
                            <? } ?>
                            <? if (false) { ?>
                                <div class="pull-left ml10">
                                    <span class="sprite sprite-product outlet"></span> Outlet Ürün
                                </div>
                            <? } ?>
                            <div class="pull-right">
                                <a href="#tabReviews" onclick="showTab('comments')"><span class="sprite sprite-question"></span></a>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                <? } ?>
                <div class="product-row">
                    <? if ($obProduct->is_saleable) { ?>
                        <div class="product-piece">
                            <label for="productQuantity">ÜRÜN ADETİ</label><br>
                            <div class="btn-group" role="group" aria-label="...">
                                <button onclick="changeQuantity('#productQuantity','down')" type="button" class="btn btn-default">-</button>
                                <input name="quantity" id="productQuantity" class="btn btn-default" value="1" type="text" min="1" max="<?= $obProduct->saleableProductCount() ?>"
                                        onblur="changeQuantity($(this))">
                                <button onclick="changeQuantity('#productQuantity','up')" type="button" class="btn btn-default">+</button>
                            </div>
                            <input type="hidden" id="productId" value="<?= $obProduct->product_id ?>"/>
                            <input type="hidden" id="variantType" value="<?= $obProduct->variant_type ?>"/>
                            <input type="hidden" id="fromSource" value="<?= (isset($_GET['from']) ? $_GET['from'] : '') ?>"/>
                        </div>
                        <a href="javascript:" class="add-to-cart btn btn-default btn-lg"
                                onclick="addToCart($('#productId').val(), $('#productQuantity').val(), $('#fromSource').val());">
                            + Sepete Ekle</a>
                        <div class="clearfix"></div>
                        <p class="cargo-info">Bu ürün tahmini <?= $obProduct->leadTime() ?> iş gününde kargoya teslim edilir.</p>
                        <div class="clearfix"></div>
                    <? } else { ?>
                        <div class="stockAlertBox">
                            Bu ürün geçici olarak temin edilemiyor.
                        </div>
                        <div class="detailsAreaCart">
                            <input type="hidden" id="productId" value="<?= $obProduct->product_id ?>"/>
                            <input type="hidden" id="fromSource" value="<?= (isset($_GET['from']) ? $_GET['from'] : '') ?>"/>
                            <a href="javascript:" class="stockReminder btn-orange" onclick="addStockAlert($('#productId').val())" role="button">
                                <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> Gelince Haber Ver
                            </a>
                        </div>
                    <? } ?>
                </div>
            </div>
        </div>
        <?= \TeknoETicaret\Widget\Block::addBlock('productInfo',
            ['productId' => $mainProductId, 'categoryId' => $obProduct->category_id, 'brandId' => $obProduct->brand_id,]) ?>
    </div>
    <div class="product-details col-lg-12 col-md-12 col-sm-12 mb30">
        <?= $tabs ?>
    </div>
</div>
<!-- widget -->
<?= \TeknoETicaret\Widget\Block::addBlock('productUnder', ['productId' => $mainProductId, 'categoryId' => $obProduct->category_id, 'brandId' => $obProduct->brand_id,]) ?>
