<?php
/**
 * @var advertisement_zone_model $zone
 * @var advertisement_model[]    $advertisements
 */
?>
<? if (count($advertisements)) { ?>
    <ul class="col-md-3 catalogBanners">
        <? foreach ($advertisements as $advertisement) { ?>
            <li>
                <a <?= (!empty($advertisement->adv_target) ? 'href="' . $advertisement->adv_target . '"' : '') ?>><img src="<?= image::getBannerUrl($advertisement) ?>"
                            class="img-responsive"></a>
            </li>
        <? } ?>
    </ul>
<? } ?>
