<?php
/**
 * @var bool   $halfLogin
 * @var string $accountMail
 * @var string $redirectTo
 */
?>
<div class="row">
    <div class="col-md-4">
        <div class="checkoutAccountBox">
            <? $loginServices = view::getLoginServices($redirectTo, ' ile Bağlan'); ?>
            <? if (count($loginServices)) { ?>
                <div class="socialLogin mb30">
                    <p class="text-center">Sosyal medya hesabınızı kullanarak giriş yapabilirsiniz.</p>
                    <div class="text-center">
                        <?= implode('', $loginServices) ?>
                    </div>
                </div>
            <? } ?>
            <div class="row">
                <div class="col-xs-10 col-xs-offset-1">
                    <? if (!$halfLogin) { ?>
                        <div class="loginOptions mb">
                            <div class="radio"><label> <input type="radio" name="loginOptions" value="loginBox" checked> Giriş yap </label></div>
                            <div class="radio"><label> <input type="radio" name="loginOptions" id="loginRegister" value="registerBox"> Üye ol </label></div>
                            <div class="radio "><label> <input type="radio" name="loginOptions" id="loginGuest" value="guestAccountBox"> Üye olmadan devam et </label></div>
                        </div>
                    <? } ?>
                    <div id="loginBox" class="optionBox">
                        <form method="post" action="/ajax/signin" role="form" id="loginForm" class="form-horizontal">
                            <input type="hidden" name="redirectTo" value="<?= $redirectTo ?>">
                            <div class="form-group">
                                <div class="col-xs-12">
                                    <label for="LoginEmail">E-Posta Adresi:</label>
                                    <? if ($halfLogin) { ?>
                                        <div>
                                            <input type="hidden" name="email" value="<?= $accountMail ?>"><?= $accountMail ?>
                                            <div class="pull-right">( <a href="/member/logout">değiştir</a> )</div>
                                        </div>
                                    <? } else { ?>
                                        <input type="email" id="LoginEmail" class="form-control" name="email">
                                    <? } ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-xs-12">
                                    <label for="LoginPassword">Parola:</label> <input type="password" id="LoginPassword" class="form-control" name="password">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-5 col-xs-6 text-left">
                                    <button class="btn btn-primary noiseBg submitButton" type="submit">Giriş Yap</button>
                                </div>
                                <div class="col-md-7 col-xs-6 text-right">
                                    <a href="/member/forgot_password">Parolamı Unuttum</a>
                                </div>
                            </div>
                        </form>
                    </div>
                    <? if (!$halfLogin) { ?>
                        <div id="registerBox" class="optionBox">
                            <form method="post" action="/ajax/signup" role="form" id="registerForm" class="form-horizontal" novalidate="novalidate">
                                <input type="hidden" name="redirectTo" value="<?= $redirectTo ?>">
                                <div class="form-group">
                                    <div class="col-xs-12 col-md-6">
                                        <label for="SignupName">Adınız:</label> <input type="text" id="SignupName" class="form-control" name="firstname">
                                    </div>
                                    <div class="col-xs-12 col-md-6">
                                        <label for="SignupSurname">Soyadınız:</label> <input type="text" id="SignupSurname" class="form-control" name="surname">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-xs-12">
                                        <label for="SignupEmail1">E-Posta Adresi:</label>
                                        <input type="email" id="SignupEmail1" class="form-control" onkeypress="return disableSpaceKey(event);" name="email">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-xs-12">
                                        <label for="SignupPassword">Parola:</label> <input type="password" id="SignupPassword" class="form-control" name="passwd">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-xs-12">
                                        <div class="checkbox">
                                            <label> <input type="checkbox" checked="checked" name="subscription" id="subscription">Önemli kampanyalardan e-posta ile haberdar olmak
                                                istiyorum.</label>
                                        </div>
                                        <div class="mt15">
                                            <button class="btn btn-primary noiseBg submitButton" type="submit">Hesabımı Oluştur</button>
                                        </div>
                                        <div class="mt15">
                                            Hesap oluşturarak <a target="_blank" href="/uyelik-sozlesmesi" class="b">üyelik sözleşmesini</a> okuduğunuzu ve kabul ettiğinizi
                                            onaylıyorsunuz.
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div id="guestAccountBox" class="optionBox">
                            <form method="post" action="/ajax/guestAccount" role="form" id="guestAccountForm" class="form-horizontal" novalidate="novalidate">
                                <input type="hidden" name="redirectTo" value="<?= $redirectTo ?>">
                                <div class="form-group">
                                    <div class="col-xs-12">
                                        <label for="SignupEmail2">E-Posta Adresi:</label>
                                        <input type="email" id="SignupEmail2" class="form-control" onkeypress="return disableSpaceKey(event);" name="email">
                                    </div>
                                </div>
                                <div class="mt15">
                                    Sipariş bilgileriniz bu e-posta adresine gönderilecektir.
                                </div>
                                <div class="mt15">
                                    <button class="btn btn-primary noiseBg submitButton" type="submit">Devam Et</button>
                                </div>
                            </form>
                        </div>
                    <? } ?>
                </div>
            </div>
        </div>
        <script>
            $(function () {
                $("input[name=loginOptions]").on("change", function () {
                    var checked = $("input[name=loginOptions]:checked").val();
                    console.log(checked);
                    $(".optionBox:visible").hide();
                    $("#" + checked).show();
                }).trigger("change");
                $('.checkoutAccountBox form').on("submit", authFormSubmit);
            });
        </script>
    </div>
    <div class="col-md-8">
        <table class="table table-bordered fixed-table membership-benefits">
            <thead>
            <tr>
                <th colspan="3" class="uye-avantajlari-baslik">Gelbura.com'a Hemen Üye Ol, 15 TL Hediye Çeki Kazan!</th>
            </tr>
            <tr>
                <th rowspan="2" style="font-size: 24px;">ÜYE OLMANIN AVANTAJLARI!</th>
                <th colspan="2">Gelbura.com’a üye olup avantajlardan faydalanabilir veya misafir olarak üye olmadan alışverişe devam edebilirsiniz.
                </th>
            </tr>
            <tr>
                <th class="uye-avantajlari-altbaslik">Misafir</th>
                <th class="uye-avantajlari-altbaslik2">Üye</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>Güvenli Ödeme Sistemi</td>
                <td><span class="sprite ok"></span></td>
                <td><span class="sprite ok"></span></td>
            </tr>
            <tr>
                <td>Hızlı Alışveriş</td>
                <td><span class="sprite minus"></span></td>
                <td><span class="sprite ok"></span></td>
            </tr>
            <tr>
                <td>Kolay Sipariş Takibi</td>
                <td><span class="sprite minus"></span></td>
                <td><span class="sprite ok"></span></td>
            </tr>
            <tr>
                <td>Müşteri Danışma Hattı</td>
                <td><span class="sprite minus"></span></td>
                <td><span class="sprite ok"></span></td>
            </tr>
            <tr>
                <td>Kupon ve Puan Sistemi</td>
                <td><span class="sprite minus"></span></td>
                <td><span class="sprite ok"></span></td>
            </tr>
            <tr>
                <td>Kişiye Özel Kampanyalar</td>
                <td><span class="sprite minus"></span></td>
                <td><span class="sprite ok"></span></td>
            </tr>
            <tr>
                <td>
                </td>
                <td>
                    <button class="btn btn-dark-grey btn-100 btn-lg submitButton" type="button" onclick="$('#loginGuest').click();$('#SignupEmail2').focus()">
                        Misafir olarak devam et
                    </button>
                </td>
                <td>
                    <button class="btn btn-grd-green btn-100 btn-lg submitButton" type="button" onclick="$('#loginRegister').click();$('#SignupName').focus()">Üye ol</button>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
