<?
/**
 * @var int             $id
 * @var string          $title
 * @var \product_item[] $products
 */
?>
<div id="<?= $id ?>" class="product-slider block">
    <h3 class="block-title"><?= $title ?></h3>
    <ul class="owl-carousel items">
        <? foreach ($products as $key => $product) { ?>
            <li class="item">
                <?= $product->generate() ?>
            </li>
        <? } ?>
    </ul>
</div>
<script>
    $(function () {
        $('#<?=$id?> .items')
            .on('initialized.owl.carousel', function () {
                $(this).find('.item').show();
            })
            .owlCarousel({
                nav: true,
                navText: ['<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>',
                    '<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>'],
                responsiveClass: true,
                responsiveBaseElement: "#<?= $id ?>",
                responsive: {
                    0: {items: 1, nav: false},
                    481: {items: 3},
                    800: {items: 4},
                    1000: {items: 5}
                },
                margin: 30,
                slideSpeed: 300,
                paginationSpeed: 400
            });
    });
</script>
