<header class="container-fluid">
    <div class="row">
        <div id="#checkoutLogoCont" class="col-md-12 col-sm-12 col-xs-12 text-center">
            <a href="/" id="checkoutLogo"><img alt="<?= \TeknoETicaret\Config\Settings::get('site.name') ?>"
                                       src="<?= view::getLogo('logo') ?>"
                                       srcset="<?= view::getLogo('logo') ?> 1x, <?= view::getLogo('logo2x') ?> 2x"/></a>
        </div>
    </div>
</header>
