<footer class="container-fluid">
    <div class="payment-options-wrapper row">
        <div class="col-lg-12 payment-options">
        </div>
    </div>
    <div class="copyright row text-center">
        <div class="col-md-12">
            <p><?= \TeknoETicaret\Config\Settings::get('site.name') ?> &copy; <?= date('Y') ?> - Tüm hakları saklıdır. </p>
        </div>
    </div><!-- #copyright# -->
    <div class="col-md-12" id="teknomavi">
        <p>Bu site <a href="https://www.teknoeticaret.com" target="_blank">Tekno E-Ticaret</a> altyapısı ile hizmet veriyor.</p>
    </div>
</footer>
<?= view::load_scripts() ?>
<?
if (!defined("DISABLE_TRACKERS")) {
    echo view::load("tracker/global_tracker");
}
?>
<!--Start of Tawk.to Script-->
<script type="text/javascript">
    var Tawk_API = Tawk_API || {}, Tawk_LoadStart = new Date();
    (function () {
        var s1 = document.createElement("script"), s0 = document.getElementsByTagName("script")[0];
        s1.async = true;
        s1.src = 'https://embed.tawk.to/5a4368debbdfe97b137fd782/default';
        s1.charset = 'UTF-8';
        s1.setAttribute('crossorigin', '*');
        s0.parentNode.insertBefore(s1, s0);
    })();
</script>
<!--End of Tawk.to Script-->
