<footer id="footer">
    <div id="privileges" class="container hidden-xs">
        <div class="row">
            <div class="col-md-3 col-sm-6">
                <div class="privilege">
                    <span class="sprite sprite-footer ssl"></span>
                    <h4>%100 Güvenli Alışveriş</h4>
                    <p>256BIT SSL sertifikası ile kart bilgileriniz güvende!</p>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="privilege">
                    <span class="sprite sprite-footer original"></span>
                    <h4>Orjinal Ürün</h4>
                    <p>GelBura’dan aldığınız bütün ürünler garantili ve orjinaldir.</p>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="privilege">
                    <span class="sprite sprite-footer return"></span>
                    <h4>Hızlı ve Kolay İade</h4>
                    <p>Satın aldığınız ürünleri kolayca iade edebilirsiniz.</p>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="privilege">
                    <span class="sprite sprite-footer cargo"></span>
                    <h4>Güvenli ve Özel Paketleme</h4>
                    <p>Siparişleriniz özenle paketlenerek kargoya teslim edilir.</p>
                </div>
            </div>
        </div>
    </div>
    <div id="banks">
        <div class="sprite banks container">
        </div>
    </div>
    <div class="footer-section black">
        <div class="container">
            <?= \TeknoETicaret\Widget\Block::addBlock('footer') ?>
        </div>
    </div>
    <div id="footer-nav" class="footer-section orange">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a href="/">ANA SAYFA</a></li>
                <li><a href="/account">HESABIM</a></li>
                <li><a href="/siparis-takip">SİPARİŞ TAKİP</a></li>
                <!-- <li><a>BAYİ GİRİŞİ</a></li> -->
                <li><a href="/iletisim">İLETİŞİM</a></li>
                <li><a href="/destek">YARDIM</a></li>
            </ul>
        </div>
    </div>
    <div id="copyright" class="footer-section black">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-sm-7"><p>Copyright © <?= \TeknoETicaret\Config\Settings::get('site.name') ?> - Tüm Hakları Saklıdır.</p>
                </div>
                <div class="col-md-6 col-sm-5 hidden-xs">
                    <div class="pull-right sprite card"></div>
                </div>
            </div>
        </div>
    </div>
    <div id="teknomavi">
        <p>Bu site <a href="https://www.teknoeticaret.com" target="_blank">Tekno E-Ticaret</a> altyapısı ile hizmet veriyor.</p>
    </div>
</footer>
<?= view::getSemanticData() ?>
<?= view::load_scripts() ?>
<?
if (!defined("DISABLE_TRACKERS")) {
    echo view::load("tracker/global_tracker");
}
?>
