<footer id="footer">
    <div id="privileges" class="container hidden-xs">
        <div class="row">
            <div class="col-md-3 col-sm-6">
                <div class="privilege">
                    <span class="sprite sprite-footer ssl"></span>
                    <h4>%100 Güvenli Alışveriş</h4>
                    <p>256BIT SSL sertifikası ile kart bilgileriniz güvende!</p>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="privilege">
                    <span class="sprite sprite-footer original"></span>
                    <h4>Orjinal Ürün</h4>
                    <p>GelBura’dan aldığınız bütün ürünler garantili ve orjinaldir.</p>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="privilege">
                    <span class="sprite sprite-footer return"></span>
                    <h4>Hızlı ve Kolay İade</h4>
                    <p>Satın aldığınız ürünleri kolayca iade edebilirsiniz.</p>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="privilege">
                    <span class="sprite sprite-footer cargo"></span>
                    <h4>Güvenli ve Özel Paketleme</h4>
                    <p>Siparişleriniz özenle paketlenerek kargoya teslim edilir.</p>
                </div>
            </div>
        </div>
    </div>
    <div id="banks">
        <div class="sprite banks container">
        </div>
    </div>
    <div class="footer-section black">
        <div class="container">
            <?= \TeknoETicaret\Widget\Block::addBlock('footer') ?>
            <div class="row">
                <div id="gelbura" class="col-md-3 col-sm-12 col-xs-12">
                    <img src="/theme/gelbura/img/logo-white.png">
                    <h3>Türkiye’nin Bilişim Tedarikçisi</h3>
                    <p>Teknoloji alanında 2004 yılından bu güne edindiğimiz tüm tecrübe ve birikimi siz müşterilerimizle
                        daha fazla paylaşabilmek için 2014 yılında www.btsiparis.com' u kurduk.</p>
                </div>
                <div class="footer-navigation col-md-2 col-sm-3 hidden-xs">
                    <h3>Kategoriler</h3>
                    <ul>
                        <li><a>Bilgisayar</a></li>
                        <li><a>Telefon</a></li>
                        <li><a>Foto &amp; Kamera</a></li>
                        <li><a>Oyun &amp; Oyun Konsolu</a></li>
                        <li><a>Ev Elektroniği &amp; TV</a></li>
                        <li><a>Güvenlik Ürünleri</a></li>
                        <li><a>Ofis &amp; Kırtasiye</a></li>
                        <li><a>Mutfak &amp; Küçük Ev Aletleri</a></li>
                        <li><a>Oto Aks &amp; Navigasyon</a></li>
                        <li><a>Outlet</a></li>
                        <li><a>Oyuncu Ekipmanları</a></li>
                    </ul>
                </div>
                <div class="footer-navigation fitHeight col-md-2 col-sm-3 col-xs-6">
                    <h3>Müşteriler</h3>
                    <ul>
                        <li><a>Yeni Üyelik</a></li>
                        <li><a>Üyelik Girişi</a></li>
                        <li><a>Şifremi Unuttum</a></li>
                        <li><a>Tedarikçi Talep Formu</a></li>
                        <li><a>Bayilik Başvurusu</a></li>
                        <li><a>Hakkımızda</a></li>
                        <li><a>Bize Ulaşın</a></li>
                        <li><a>Gizlilik Politikası</a></li>
                        <li><a>Kullanım Şartları</a></li>
                    </ul>
                </div>
                <div class="footer-navigation fitHeight col-md-2 col-sm-3 col-xs-6">
                    <h3>Destek</h3>
                    <ul>
                        <li><a>Alışveriş Sepeti</a></li>
                        <li><a>Mesafeli Satış Sözleşmesi</a></li>
                        <li><a>Ödeme ve Teslimat</a></li>
                        <li><a>Havale Bildirim Formnu</a></li>
                        <li><a>İade, İptal ve Değişim</a></li>
                    </ul>
                </div>
                <div id="social" class="col-md-3 col-sm-3 col-xs-12">
                    <div class="c-row">
                        <h3>Bizi Takip Edin!</h3>
                        <ul class="social-wrapper">
                            <li class="sprite social fb"><a href="http://facebook.com"></a></li>
                            <li class="sprite social ins"><a></a></li>
                            <li class="sprite social tw"><a></a></li>
                            <li class="sprite social pin"><a></a></li>
                            <li class="sprite social go"><a></a></li>
                            <li class="sprite social yt"><a></a></li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="c-row">
                        <h3>Haberdar Olun!</h3>
                        <div id="newsletter" class="input-group">
                            <input type="text" class="form-control" placeholder="mail adresiniz">
                            <span class="input-group-btn">
                            <button class="btn btn-default sprite mail" type="button"></button>
                        </span>
                        </div>
                    </div>
                    <div class="c-row">
                        <div class="phone">
                            <h3>Mutlu Müşteri Hattı</h3>
                            <p>Hafta İçi 09:00 - 18:00</p>
                            <h2>0216 344 44 22</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="footer-nav" class="footer-section orange">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a>ANA SAYFA</a></li>
                <li><a>HESABIM</a></li>
                <li><a>SİPARİŞ TAKİP</a></li>
                <li><a>BAYİ GİRİŞİ</a></li>
                <li><a>İLETİŞİM</a></li>
                <li><a>YARDIM</a></li>
            </ul>
        </div>
    </div>
    <div id="copyright" class="footer-section black">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-sm-7"><p>Copyright © <?= \TeknoETicaret\Config\Settings::get('site.name') ?> - Tüm Hakları Saklıdır.</p>
                </div>
                <div class="col-md-6 col-sm-5 hidden-xs">
                    <div class="pull-right sprite card"></div>
                </div>
            </div>
        </div>
    </div>
    <div id="teknomavi">
        <p>Bu site <a href="https://www.teknoeticaret.com" target="_blank">Tekno E-Ticaret</a> altyapısı ile hizmet veriyor.</p>
    </div>
</footer>
<?= view::getSemanticData() ?>
<?= view::load_scripts() ?>
<?
if (!defined("DISABLE_TRACKERS")) {
    echo view::load("tracker/global_tracker");
}
?>
