<?
/**
 * @var category_model[] $catalogs
 * @var category_model   $category
 */
view::requireAsset('masonry');
?>
<div id="navigation" class="visible-md visible-lg">
    <div class="container">
        <nav id="main-menu" class="">
            <ul class="nav navbar-nav">
                <li class="nav-logo"><a href="/" id="nav-logo"><img alt="<?= \TeknoETicaret\Config\Settings::get('site.name') ?>" src="<?= view::getLogo('fixedNav') ?>"
                                srcset="<?= view::getLogo('fixedNav') ?> 1x, <?= view::getLogo('fixedNav2x') ?> 2x"/></a></li>
                <? if (count($catalogs)) { ?>
                    <? foreach ($catalogs as $catalog) { ?>
                        <? if (isset($childCategories[$catalog['id']]) && count($childCategories[$catalog['id']])) { ?>
                            <li class="dropdown-opener"><a href="<?= $catalog['link'] ?>"><span><?= $catalog['name'] ?></span></a>
                                <div class="dropdown-menu">
                                    <div class="col-md-9">
                                        <div class="row masonry">
                                            <? foreach ($childCategories[$catalog['id']] as $category) { ?>
                                                <div class="col-md-4 masonry-item"><a href="<?= $category['link'] ?>"><?
                                                        echo $category['name'];
                                                        if (isset($childCategories[$category['id']]) && count($childCategories[$category['id']])) {
                                                            $subCats = [];
                                                            foreach ($childCategories[$category['id']] as $subCategory) {
                                                                $subCats[] = $subCategory['name'];
                                                                if (count($subCats) > 8) {
                                                                    $subCats[] = '...';
                                                                    break;
                                                                }
                                                            }
                                                            echo '<span>' . implode(', ', $subCats) . '</span>';
                                                        }
                                                        ?></a>
                                                </div>
                                            <? } ?>
                                        </div>
                                        <div class="clear"></div>
                                    </div>
                                    <?= \TeknoETicaret\Advertisement\Zone::renderGlobal('CatalogMenuItems', ['categoryId' => $catalog['id']]) ?>
                                </div>
                            </li>
                        <? } else { ?>
                            <li>
                                <a href="<?= $catalog['link'] ?>"><?= $catalog['name'] ?></a>
                            </li>
                        <? } ?>
                    <? } ?>
                <? } ?>
            </ul>
        </nav>
    </div>
</div>
<script type="text/javascript">
    $(function () {
        $('#navigation').on('mouseover', '.dropdown-opener', function () {
            if ($(this).data('masonry') != true) {
                $(this).find('.masonry').masonry({
                    itemSelector: '.masonry-item'
                });
                $(this).data('masonry', true);
            }
        });
    });
</script>
